/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */
package com.radaee.viewlib;

public final class R {
	public static final class drawable {
		public static final int bar_back = 0x7f020000;
		public static final int btn_annot_ellipse = 0x7f020001;
		public static final int btn_annot_ink = 0x7f020002;
		public static final int btn_annot_line = 0x7f020003;
		public static final int btn_annot_note = 0x7f020004;
		public static final int btn_annot_rect = 0x7f020005;
		public static final int btn_back = 0x7f020006;
		public static final int btn_cancel = 0x7f020007;
		public static final int btn_done = 0x7f020008;
		public static final int btn_ink = 0x7f020009;
		public static final int btn_left = 0x7f02000a;
		public static final int btn_outline = 0x7f02000b;
		public static final int btn_perform = 0x7f02000c;
		public static final int btn_remove = 0x7f02000d;
		public static final int btn_right = 0x7f02000e;
		public static final int btn_search = 0x7f02000f;
		public static final int btn_select = 0x7f020010;
		public static final int btn_view = 0x7f020011;
		public static final int btn_view_dual = 0x7f020012;
		public static final int btn_view_single = 0x7f020013;
		public static final int btn_view_vert = 0x7f020014;
		public static final int file03 = 0x7f020015;
		public static final int folder0 = 0x7f020016;
		public static final int folder1 = 0x7f020017;
		public static final int folder2 = 0x7f020018;
		public static final int menu_back = 0x7f020019;
		public static final int pdf_custom_stamp = 0x7f02001a;
		public static final int pt_end = 0x7f02001b;
		public static final int pt_start = 0x7f02001c;
	}
	public static final class id {
		public static final int annot_combo = 0x7f07002a;
		public static final int annot_text = 0x7f07002b;
		public static final int btn_annot = 0x7f07000c;
		public static final int btn_annot_ink = 0x7f070008;
		public static final int btn_annot_line = 0x7f070005;
		public static final int btn_annot_note = 0x7f070009;
		public static final int btn_annot_oval = 0x7f070007;
		public static final int btn_annot_rect = 0x7f070004;
		public static final int btn_annot_stamp = 0x7f070006;
		public static final int btn_back = 0x7f070000;
		public static final int btn_edit = 0x7f070001;
		public static final int btn_find = 0x7f07000b;
		public static final int btn_goto = 0x7f070024;
		public static final int btn_left = 0x7f070010;
		public static final int btn_outline = 0x7f07000e;
		public static final int btn_perform = 0x7f070002;
		public static final int btn_remove = 0x7f070003;
		public static final int btn_right = 0x7f07000f;
		public static final int btn_select = 0x7f07000d;
		public static final int btn_view = 0x7f07000a;
		public static final int chk_show = 0x7f07001c;
		public static final int curl_view = 0x7f070025;
		public static final int dlg_input = 0x7f07001a;
		public static final int dlg_show_note = 0x7f070014;
		public static final int imageView1 = 0x7f07002d;
		public static final int imageView2 = 0x7f070030;
		public static final int imageView3 = 0x7f070032;
		public static final int lab_content = 0x7f070017;
		public static final int lab_page = 0x7f070013;
		public static final int lab_subj = 0x7f070015;
		public static final int lst_outline = 0x7f070019;
		public static final int pdf_nav = 0x7f070029;
		public static final int pdf_pager = 0x7f070026;
		public static final int pdf_view = 0x7f070027;
		public static final int rad_copy = 0x7f07001e;
		public static final int rad_group = 0x7f07001d;
		public static final int rad_highlight = 0x7f07001f;
		public static final int rad_squiggly = 0x7f070022;
		public static final int rad_strikeout = 0x7f070021;
		public static final int rad_underline = 0x7f070020;
		public static final int seek_page = 0x7f070012;
		public static final int textView1 = 0x7f07002e;
		public static final int txt_content = 0x7f070018;
		public static final int txt_find = 0x7f070011;
		public static final int txt_name = 0x7f070023;
		public static final int txt_password = 0x7f07001b;
		public static final int txt_path = 0x7f070028;
		public static final int txt_subj = 0x7f070016;
		public static final int view_dual = 0x7f070031;
		public static final int view_single = 0x7f07002f;
		public static final int view_vert = 0x7f07002c;
	}
	public static final class layout {
		public static final int bar_act = 0x7f030000;
		public static final int bar_annot = 0x7f030001;
		public static final int bar_cmd = 0x7f030002;
		public static final int bar_find = 0x7f030003;
		public static final int bar_seek = 0x7f030004;
		public static final int dlg_note = 0x7f030005;
		public static final int dlg_outline = 0x7f030006;
		public static final int dlg_pswd = 0x7f030007;
		public static final int dlg_text = 0x7f030008;
		public static final int item_outline = 0x7f030009;
		public static final int pdf_curl = 0x7f03000a;
		public static final int pdf_fragment = 0x7f03000b;
		public static final int pdf_layout = 0x7f03000c;
		public static final int pdf_nav = 0x7f03000d;
		public static final int pop_combo = 0x7f03000e;
		public static final int pop_edit = 0x7f03000f;
		public static final int pop_view = 0x7f030010;
	}
	public static final class raw {
		public static final int arimo = 0x7f040000;
		public static final int arimob = 0x7f040001;
		public static final int arimobi = 0x7f040002;
		public static final int arimoi = 0x7f040003;
		public static final int cmaps = 0x7f040004;
		public static final int cmyk_rgb = 0x7f040005;
		public static final int cousine = 0x7f040006;
		public static final int cousineb = 0x7f040007;
		public static final int cousinebi = 0x7f040008;
		public static final int cousinei = 0x7f040009;
		public static final int rdf008 = 0x7f04000a;
		public static final int rdf013 = 0x7f04000b;
		public static final int tinos = 0x7f04000c;
		public static final int tinosb = 0x7f04000d;
		public static final int tinosbi = 0x7f04000e;
		public static final int tinosi = 0x7f04000f;
		public static final int umaps = 0x7f040010;
	}
	public static final class string {
		public static final int app_name = 0x7f050000;
	}
	public static final class style {
		public static final int AppBaseTheme = 0x7f060000;
		public static final int AppTheme = 0x7f060001;
	}
}
